name: Build

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

permissions:
  contents: write
  discussions: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup Node.js and Pnpm
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: 'pnpm'
      - name: Install Dependency
        run: pnpm install

      - name: Build Page
        run: pnpm zip

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            .output/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
